[package]
authors = ["Jeff Muizelaar <jmuizelaar@mozilla.com>"]
name = "jrmuizel-pdf-info"
version = "0.1.0"

[dependencies]
encoding = "0.2.33"
euclid = "0.15.1"
flate2 = "0.2.17"
lopdf = "0.12"
adobe-cmap-parser = "0.2.0"
type1-encoding-parser = "0.1.0"
postscript = "0.11.1"
