[package]
name = "jrmuizel-pdf-info"
version = "0.1.0"
authors = ["Jeff Muizelaar <jmuizelaar@mozilla.com>"]

[dependencies]
encoding = "0.2.33"
flate2 = "0.2.17"
pom = "0.8.1"
postscript = "0.11.1"
lopdf = "0.8"

